#!/usr/bin/env python3
"""Build the AGENTS.md a non-Claude harness reads, from this repo's Claude config.

Codex reads one always-on instructions file and follows no `@` imports, and it
has no `paths:` scoping for rule files. So the profile's CLAUDE.md is flattened:
each `@` import is inlined, the path-scoped rules become an index to read on
demand, and a closing section translates the Claude-specific terms the skills use.

Usage:
  python3 scripts/agents_md.py --profile personal > ~/.codex/AGENTS.md
"""

import argparse
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# install.sh greps for the text after "<!-- " to tell this file from a hand-written one.
MARKER = "<!-- generated by claude-config/scripts/agents_md.py; edit the sources, not this file -->"
IMPORT_LINE = re.compile(r"^@(\S+)\s*$")
CLAUDE_HOME = "~/.claude/"
# Claude Code gets this as a system-prompt section from the mods plugin; Codex runs no mods.
REPLY_STYLE = os.path.join(ROOT, "plugins", "mods", "prompts", "reply-style.md")

HARNESS_NOTES = """\
## Reading Claude Code skills and rules in another harness

The skills and rules above were written for Claude Code. Read their Claude-specific
terms this way:

| Where a skill says | Do this |
| --- | --- |
| `${CLAUDE_PLUGIN_ROOT}` or `<PLUGIN_ROOT>` | The plugin directory: two levels above the skill's own directory, after resolving symlinks. For a skill linked at `~/.agents/skills/ship` that is `$(dirname "$(dirname "$(realpath ~/.agents/skills/ship)")")`. |
| `Agent({...})`, "dispatch a subagent" | Hand the prompt to a subagent if you can start one. Otherwise do that work yourself, following the same prompt and returning what it asks for. Ignore `model:` and `subagent_type:`; they name Claude models and agent types. |
| `AskUserQuestion` | Ask the user directly. List the options with your recommendation first. |
| `/plugin:skill`, the `Skill` tool, "use the X skill" | Read skill X's `SKILL.md`, from `.agents/skills/X/` in the repo or `~/.agents/skills/X/`, and follow it. The user invokes one as `$X`. |
| A repo's `CLAUDE.md` or `.claude/rules/` | Repo instructions, the same kind as `AGENTS.md`. Read them when present. |
"""

# Kept apart from HARNESS_NOTES because evals/run.py gives eval sandboxes the
# notes alone: each sandbox is a throwaway checkout on main, where these rules
# would forbid the very edits a case asks for.
HOOK_RULES = """## Rules Claude Code enforces with hooks

None of those hooks run here, so hold to their rules yourself: commit only on a
branch, never on the default branch; make edits in a git worktree, not in a
repo's main checkout; and run the repo's own build, lint, typecheck and tests
before every push.
"""


def read(path: str) -> str:
    with open(path, encoding="utf-8") as handle:
        return handle.read()


def resolve_import(target: str) -> str | None:
    """Find the file an `@` import names.

    Args:
        target: The path after the `@`, such as `~/.claude/shared-rules.md`.

    Returns:
        The file to read, or None when it does not exist on this machine.
    """
    # install.sh links ~/.claude/<x> to this repo's <x>, so read the repo copy:
    # it exists on a fresh machine and in CI, where the link does not.
    if target.startswith(CLAUDE_HOME):
        in_repo = os.path.join(ROOT, target[len(CLAUDE_HOME):])
        if os.path.isfile(in_repo):
            return in_repo
    path = os.path.expanduser(target)
    return path if os.path.isfile(path) else None


def inline_imports(text: str) -> str:
    """Replace each `@path` line with that file's contents, one level deep.

    A missing import is dropped silently, the way Claude Code treats it, so a
    profile that imports an optional local file still builds.

    Args:
        text: A CLAUDE.md body.

    Returns:
        The body with every import inlined.
    """
    lines = []
    for line in text.splitlines():
        match = IMPORT_LINE.match(line)
        if not match:
            lines.append(line)
            continue
        path = resolve_import(match.group(1))
        if path:
            lines.append(read(path).rstrip())
    return "\n".join(lines)


def frontmatter(text: str) -> tuple[list[str], str]:
    """Pull the `paths:` list and `description:` out of a rule file's frontmatter.

    Every indented `- item` counts as a path, which holds while `paths:` is the
    only list key a rule file carries.

    Args:
        text: A rule file's contents.

    Returns:
        The path globs and the description; empty when absent.
    """
    if not text.startswith("---\n"):
        return [], ""
    header = text[4:text.find("\n---", 4)]
    paths = re.findall(r'^\s+-\s+"?([^"\n]+)"?\s*$', header, re.MULTILINE)
    description = re.search(r"^description:\s*(.+)$", header, re.MULTILINE)
    return paths, description.group(1).strip().strip("\"'") if description else ""


def rules_index() -> str:
    """List the path-scoped rules as an index the agent reads on demand.

    Returns:
        A markdown section naming each rule file and the files it governs.
    """
    entries = []
    for path in sorted(glob.glob(os.path.join(ROOT, "rules", "*.md"))):
        globs, description = frontmatter(read(path))
        name = os.path.basename(path)
        entries.append(f"- `~/.claude/rules/{name}`: {description} Applies to {', '.join(f'`{g}`' for g in globs)}.")
    return (
        "## Rules by file type\n\n"
        "Before reading or editing a file, read each rule file whose patterns match it,\n"
        "once per session. `~/.claude/rules-reference.md` holds the full rationale.\n\n"
        + "\n".join(entries)
        + "\n"
    )


def build(profile: str) -> str:
    """Assemble the whole AGENTS.md for one profile.

    Args:
        profile: A directory name under `profiles/`.

    Returns:
        The file's contents.
    """
    claude_md = read(os.path.join(ROOT, "profiles", profile, "CLAUDE.md"))
    return "\n\n".join([MARKER, inline_imports(claude_md).strip(), read(REPLY_STYLE).strip(), rules_index().strip(), HARNESS_NOTES.strip(), HOOK_RULES.strip()]) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--profile", default="personal")
    args = parser.parse_args()
    sys.stdout.write(build(args.profile))
    return 0


if __name__ == "__main__":
    sys.exit(main())
